<?php

/**
 * SiteFiles
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SiteFiles extends BaseSiteFiles
{
	public function setUp() {
		$this->hasMany('SiteGalleries as Galleries', array(
			'local' => 'id_image',
			'foreign' => 'id_gallery',
			'refClass' => 'SiteGalleriesImages'));

		$this->hasMany('SiteGalleriesImages as GalleryImages', array(
			'local' => 'id',
			'foreign' => 'id_image'));

		$this->hasMany('SiteNews as News', array(
			'local' => 'id_file',
			'foreign' => 'id_news',
			'refClass' => 'SiteNewsFiles'));

		$this->hasMany('SiteFilesMeta as Meta', array(
			'local' => 'id',
			'foreign' => 'id_file'));
	}

	public function generateThumbnail()
	{
		if ($this->type == 'Immagine')
		{
			$img = new SimpleImage(200, 200, array('r' => 0, 'g' => 0, 'b' => 0));
			$img->load(MEDIA_FOLDER.$this->filename);
			$img->resizeCrop(200, 200);
			$img->save(MEDIA_FOLDER.'th_'.$this->filename, $img->image_type);
		}
	}
}