<?php

/**
 * SiteGalleries
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SiteGalleries extends BaseSiteGalleries
{
	public function setUp() {
		$this->hasMany('SiteFiles as Images', array(
			'local' => 'id_gallery',
			'foreign' => 'id_image',
			'refClass' => 'SiteGalleriesImages'));

		$this->hasMany('SiteGalleriesImages as GalleryImage', array(
			'local' => 'id',
			'foreign' => 'id_gallery'));

		$this->hasOne('SysLanguages as Language', array(
			'local' => 'id_language',
			'foreign' => 'id'));

		$this->hasOne('SysPages as Page', array(
			'local' => 'id_page',
			'foreign' => 'id'));
	}

	public function getImages()
	{
		$images = SiteGalleriesImagesTable::getInstance()->createQuery('a')
				->leftJoin('a.Image g')
				->where('a.id_gallery = ?', $this->id)
				->orderBy('sort_order ASC')
				->execute();

		return $images;
	}
}