<?php

/**
 * SiteContents
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SiteContents extends BaseSiteContents
{
	public function setUp() {
		$this->hasOne('SysLanguages as Language', array(
				'local' => 'id_language',
				'foreign' => 'id'));
		
		$this->hasOne('SysPages as Page', array(
				'local' => 'id_page',
				'foreign' => 'id'));
	}
}