<?php

/**
 * SiteFilesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SiteFilesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SiteFilesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SiteFiles');
    }
}