<?php

/**
 * SiteContentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SiteContentsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SiteContentsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SiteContents');
    }
}