<?php

/**
 * SiteNewsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SiteNewsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SiteNewsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SiteNews');
    }
}