<?php

/**
 * SiteGalleriesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SiteGalleriesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SiteGalleriesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SiteGalleries');
    }
}