<?php

/**
 * SiteGalleriesImages
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SiteGalleriesImages extends BaseSiteGalleriesImages
{
	public function setUp() {
		$this->hasOne('SiteFiles as Image', array(
			'local' => 'id_image',
			'foreign' => 'id'));

		$this->hasOne('SiteGalleries as Gallery', array(
			'local' => 'id_gallery',
			'foreign' => 'id'));
	}
}