<?php

/**
 * SiteNewsFilesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SiteNewsFilesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SiteNewsFilesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SiteNewsFiles');
    }
}