<?php

/**
 * SiteFilesMetaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SiteFilesMetaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SiteFilesMetaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SiteFilesMeta');
    }
}