<?php

/**
 * SysAdminRolesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SysAdminRolesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SysAdminRolesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SysAdminRoles');
    }
}