<?php

/**
 * SysAdmins
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SysAdmins extends BaseSysAdmins
{
	public function setUp() {
		$this->hasOne('SysAdminRoles as Role', array(
				'local' => 'id_role',
				'foreign' => 'id'));
		$this->hasMany('SysRolesMenus as Menus', array(
				'orderBy' => 'sort_order',
				'local' => 'id_role',
				'foreign' => 'id_role'));
	}
}