<?php

/**
 * SysAdminsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SysAdminsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SysAdminsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SysAdmins');
    }
}