<?php

/**
 * SysAliasesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SysAliasesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SysAliasesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SysAliases');
    }
}