<?php

/**
 * SysAdminMenusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SysAdminMenusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SysAdminMenusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SysAdminMenus');
    }
}