<?php

/**
 * SysDictionaryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SysDictionaryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SysDictionaryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SysDictionary');
    }
}