<?php

/**
 * SysLanguagesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SysLanguagesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SysLanguagesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SysLanguages');
    }
}