<?php

/**
 * SysRolesMenus
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SysRolesMenus extends BaseSysRolesMenus
{
	public function setUp() {
		$this->hasOne('SysAdminRoles as Role', array(
				'local' => 'id_role',
				'foreign' => 'id'));
		$this->hasOne('SysAdminMenus as Menu', array(
				'local' => 'id_menu',
				'foreign' => 'id'));
		$this->hasOne('SysRolesMenus as Parent', array(
				'local' => 'id_parent',
				'foreign' => 'id'));
		$this->hasMany('SysRolesMenus as Children', array(
				'orderBy' => 'sort_order',
				'local' => 'id',
				'foreign' => 'id_parent'));
	}
}