<?php

/**
 * SysRolesMenusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SysRolesMenusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SysRolesMenusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SysRolesMenus');
    }
}