<?php

/**
 * SysSessionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SysSessionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SysSessionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SysSessions');
    }
}