<?php

/**
 * SysSlugsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SysSlugsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SysSlugsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SysSlugs');
    }
}