<?php

/**
 * SysTranslationsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SysTranslationsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SysTranslationsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SysTranslations');
    }
}